In [9]:
import numpy as np

In [5]:
arr1 = np.array([1, 2, 3, 4, 5, 6])
arr2 = arr1.reshape(2,3)

print("1차원 배열")
print(arr1)

print("2차원 배열")
print(arr2)

1차원 배열
[1 2 3 4 5 6]
2차원 배열
[[1 2 3]
 [4 5 6]]


In [6]:
arr2d = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
arr4d = arr2d.reshape(2,2,1,3)

print("2차원 배열")
print(arr2d)

print("4차원 배열")
print(arr4d)

2차원 배열
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
4차원 배열
[[[[ 1  2  3]]

  [[ 4  5  6]]]


 [[[ 7  8  9]]

  [[10 11 12]]]]


In [7]:
arr3d = np.array([[[1,2],[3,4,]],
                  [[5,6],[7,8]],
                  [[9,10],[11,12]]])
arr2d = arr3d.reshape(6,2)

print("3차원 배열")
print(arr3d)

print("2차원 배열")
print(arr2d)

3차원 배열
[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]]
2차원 배열
[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]]


In [11]:
arr3d = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
arr4d = arr3d.reshape(2,2,1,2)

arr4d

array([[[[1, 2]],

        [[3, 4]]],


       [[[5, 6]],

        [[7, 8]]]])

# flatten / ravel
* ravel 원본을 참조하기 때문에 값이 바뀜

In [12]:
arr2d = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr1d = arr2d.flatten()

print(arr2d)

print(arr1d)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[1 2 3 4 5 6 7 8 9]


In [13]:
arr2d = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr1d = arr2.ravel()

print(arr2d)

print(arr1d)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[1 2 3 4 5 6]


In [20]:
arr2d = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr_fla = arr2d.flatten()
arr_rav = arr2d.ravel()

arr_fla[0] = 99
arr_rav[-1] = 99

print(arr_fla,"\n")
print(arr_rav,"\n")
print(arr2d)

[99  2  3  4  5  6  7  8  9] 

[ 1  2  3  4  5  6  7  8 99] 

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8 99]]


In [24]:
arr = np.arange(24).reshape(2,3,4)
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [27]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr1 = arr.reshape(9,)
arr_fla = arr.flatten()
arr_rav = arr.ravel()

print(arr1, "\n")
print(arr_fla, "\n")
print(arr_rav)

[1 2 3 4 5 6 7 8 9] 

[1 2 3 4 5 6 7 8 9] 

[1 2 3 4 5 6 7 8 9]


# 전치행렬

In [3]:
arr = np.array([[1,2,3,4,5,6]])
arr.T

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [4]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr.transpose()

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [5]:
arr3d = np.arange(1, 13).reshape(2, 2, 3)
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [6]:
arr3dt = arr3d.transpose((2,1,0)) # 축의 번호를 뜻함. 원래는 (0,1,2)
print(arr3dt)

[[[ 1  7]
  [ 4 10]]

 [[ 2  8]
  [ 5 11]]

 [[ 3  9]
  [ 6 12]]]


In [10]:
import numpy as np
from PIL import Image

img = Image.open('C:/users/pc/downloads/image.jpg')
img.show()

In [3]:
arr = np.asarray(img)
print("이미지 크기", arr.shape)

이미지 크기 (2000, 2000, 3)


In [7]:
arr_T = arr.transpose((1,0,2))
print("전치된 이미지 크기", arr_T.shape)

전치된 이미지 크기 (2000, 2000, 3)


In [8]:
img_T = Image.fromarray(arr_T.astype(np.uint8))
img_T.show()

In [5]:
arr1da = np.array([1,2])
arr1db = np.array([3,4])

arr1dc = np.concatenate([arr1da, arr1db], axis=0) # axis는 병합 기준
print(arr1dc)


[1 2 3 4]


In [11]:
arr2da =np.array([[1,2],[3,4]])
arr2db =np.array([[5,6]])

arr2dc = np.concatenate((arr2da,arr2db),axis=0)
arr2dc

array([[1, 2],
       [3, 4],
       [5, 6]])

* hstack 은 horizontal 수평으로  / hsplit
* vstack 은 vertical 수직으로 / vsplit

In [16]:
a = np.array([1,2,3,4,5,6])
b = np.split(a, 3)
print(b)

[array([1, 2]), array([3, 4]), array([5, 6])]


In [35]:
c = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
d = np.split(c, 2)
print(d)

[array([[1, 2, 3],
       [4, 5, 6]]), array([[ 7,  8,  9],
       [10, 11, 12]])]
