# 선형 대수

In [1]:
import numpy as np

In [2]:
v1 = np.array([1, 5, -4])

arr1 = np.array([[1,2,3],[4,5,6]])
print(v1)
print(arr1)

[ 1  5 -4]
[[1 2 3]
 [4 5 6]]


# 내적

In [3]:
v1 = np.array([1,2,3])
v2 = np.array([5,0,-7])
np.dot(v1, v2)

-16

In [4]:
v1 = np.array([5,0])
v2 = np.array([0,4])
np.dot(v1, v2)

0

In [5]:
v1 = np.array([5,0])
v2 = np.array([-2,4])
np.dot(v1, v2)

-10

In [6]:
arr1 = np.array([[1,2],[3,4],[5,6]])
arr2 = np.array([[6,23],[-1,7],[8,9]])

np.dot(arr1,arr2)

ValueError: shapes (3,2) and (3,2) not aligned: 2 (dim 1) != 3 (dim 0)

In [7]:
np.dot(arr1, arr2.T)

array([[ 52,  13,  26],
       [110,  25,  60],
       [168,  37,  94]])

In [8]:
np.dot(arr1.T, arr2)

array([[ 43,  89],
       [ 56, 128]])

In [9]:
from sklearn.datasets import load_iris

In [10]:
iris = load_iris()
# iris.data
# iris['data']
X = iris.data
Y = iris.target

In [11]:
print(X.shape)
print(Y.shape)

(150, 4)
(150,)


In [12]:
X[Y == 0] # y가 true인 것들만 x에서 가져온다
for i in range(3):
    print(iris.target_names[i])
    print(X[Y == i].mean(axis=0))
    print(X[Y == i].std(axis=0))

setosa
[5.006 3.428 1.462 0.246]
[0.34894699 0.37525458 0.17191859 0.10432641]
versicolor
[5.936 2.77  4.26  1.326]
[0.51098337 0.31064449 0.46518813 0.19576517]
virginica
[6.588 2.974 5.552 2.026]
[0.62948868 0.31925538 0.54634787 0.27188968]


In [57]:
def cos_sim(sample, standard):
    return np.dot(sample, standard) / (np.linalg.norm(sample, axis=1) * np.linalg.norm(standard))
    # / 뒤에 거는 벡터 크기 구하는 함수
    # cos0 == a.b / |a||b|

In [14]:
X[Y == 0][0:1]
# 샘플 하나만 가져올 때

array([[5.1, 3.5, 1.4, 0.2]])

In [15]:
sample = X[Y == 0][0:1]
setosa = X[Y == 0].mean(axis=0)
cos_sim(sample, setosa)
# 유사도

array([0.99987243])

(150, 4) . (4, 1) -> (150, 1)  

(150, 4) . (4, ) -> (150, )


In [16]:
np.dot(X, setosa).shape

(150,)

In [17]:
setosa = X[Y == 0].mean(axis=0)
cos_sim(X, setosa)

array([0.99987243, 0.99875167, 0.99991528, 0.99958212, 0.99962191,
       0.99944014, 0.99931449, 0.99994583, 0.99958036, 0.99898192,
       0.999891  , 0.99943689, 0.99890941, 0.99930953, 0.99763752,
       0.99786694, 0.99855875, 0.99987249, 0.99989947, 0.99921484,
       0.99897733, 0.99939929, 0.9958143 , 0.99823312, 0.99697821,
       0.99780355, 0.99944933, 0.9999334 , 0.99964213, 0.99926624,
       0.99897565, 0.99905228, 0.99746199, 0.99798723, 0.99922182,
       0.99883515, 0.99863146, 0.99915394, 0.99998938, 0.99989107,
       0.99955949, 0.99204386, 0.99961181, 0.99821815, 0.99759829,
       0.99908581, 0.99916021, 0.99992803, 0.99988308, 0.99981486,
       0.93380331, 0.931688  , 0.92351558, 0.91259304, 0.91942619,
       0.91367682, 0.92510393, 0.93834199, 0.92598037, 0.92216769,
       0.91752488, 0.92938985, 0.91939376, 0.91485821, 0.94537314,
       0.93674082, 0.91410836, 0.93026818, 0.89874561, 0.92739332,
       0.90930284, 0.93594771, 0.89768757, 0.914521  , 0.93277

In [18]:
setosa = X[Y == 0].mean(axis=0)
versicolor = X[Y == 1].mean(axis=0)
verginica = X[Y == 2].mean(axis=0)

print(setosa)
print(versicolor)
print(verginica)

[5.006 3.428 1.462 0.246]
[5.936 2.77  4.26  1.326]
[6.588 2.974 5.552 2.026]


In [19]:
setosa_cos = cos_sim(X, setosa)
versicolor_cos = cos_sim(X, versicolor)
verginica_cos = cos_sim(X, verginica)

In [20]:
# np.concatenate([setosa_cos, versicolor_cos, verginica_cos], axis=1).shape
# 1차원인라서 오류남.
cos = np.stack([setosa_cos, versicolor_cos, verginica_cos])
cos.shape

(3, 150)

In [21]:
np.sum(np.argmax(cos, axis=0) == Y) / len(Y)
# np.argmax(cos, axis=0) - 예측결과
# Y - 정답

0.9733333333333334

In [65]:
setosa = X[Y == 0].mean(axis=0)
versicolor = X[Y == 1].mean(axis=0)
verginica = X[Y == 2].mean(axis=0)

setosa_cos = cos_sim(X, setosa)
versicolor_cos = cos_sim(X, versicolor)
verginica_cos = cos_sim(X, verginica)

cos = np.stack([setosa_cos, versicolor_cos, verginica_cos])

np.sum(np.argmax(cos, axis=0) == Y) / len(Y)

0.9733333333333334

In [76]:
temp = []
for i in range(3):
    means = X[Y == i].mean(axis=0)
    cos = cos_sim(X, means)
    temp.append(cos)
result_cos = np.stack(temp)
print(np.sum(np.argmax(result_cos, axis=0) == Y) / len(Y))


0.9733333333333334


In [81]:
temp = []
for i in range(3):
    means = X[Y == i].mean(axis=0)
    cos = cos_sim(X, means)
    temp.append(cos)
result_cos = np.stack(temp)
print(np.sum(np.argmax(result_cos, axis=0) == Y) / len(Y))

0.9733333333333334


In [124]:
arr1 = np.array([1,2,3,4,5])
arr1

array([1, 2, 3, 4, 5])

In [125]:
arr2 = arr1[1:3].copy()
arr2

array([2, 3])

In [126]:
arr2 *= 10
arr2

array([20, 30])

In [127]:
arr1

array([1, 2, 3, 4, 5])

In [134]:
print(id(arr1[1]))
print(id(arr2[0]))

2278726931824
2278726938800
