# 선형 대수

In [2]:
import numpy as np

In [3]:
v1 = np.array([1, 5, -4])

arr1 = np.array([[1,2,3],[4,5,6]])
print(v1)
print(arr1)

[ 1  5 -4]
[[1 2 3]
 [4 5 6]]


# 내적

In [3]:
v1 = np.array([1,2,3])
v2 = np.array([5,0,-7])
np.dot(v1, v2)

-16

In [6]:
v1 = np.array([5,0])
v2 = np.array([0,4])
np.dot(v1, v2)

0

In [7]:
v1 = np.array([5,0])
v2 = np.array([-2,4])
np.dot(v1, v2)

-10

In [3]:
arr1 = np.array([[1,2],[3,4],[5,6]])
arr2 = np.array([[6,23],[-1,7],[8,9]])

np.dot(arr1,arr2)

ValueError: shapes (3,2) and (3,2) not aligned: 2 (dim 1) != 3 (dim 0)

In [6]:
np.dot(arr1, arr2.T)

array([[ 52,  13,  26],
       [110,  25,  60],
       [168,  37,  94]])

In [7]:
np.dot(arr1.T, arr2)

array([[ 43,  89],
       [ 56, 128]])

In [4]:
from sklearn.datasets import load_iris

In [5]:
iris = load_iris()
# iris.data
# iris['data']
X = iris.data
Y = iris.target

In [6]:
print(X.shape)
print(Y.shape)

(150, 4)
(150,)


In [7]:
X[Y == 0] # y가 true인 것들만 x에서 가져온다
for i in range(3):
    print(iris.target_names[i])
    print(X[Y == i].mean(axis=0))
    print(X[Y == i].std(axis=0))

setosa
[5.006 3.428 1.462 0.246]
[0.34894699 0.37525458 0.17191859 0.10432641]
versicolor
[5.936 2.77  4.26  1.326]
[0.51098337 0.31064449 0.46518813 0.19576517]
virginica
[6.588 2.974 5.552 2.026]
[0.62948868 0.31925538 0.54634787 0.27188968]


In [17]:
def cos_sim(sample, standard):
    return np.dot(sample, standard) / (np.linalg.norm(sample, axis=1) * np.linalg.norm(standard)) 
    # / 뒤에 거는 벡터 크기 구하는 함수
    # cos0 == a.b / |a||b|

In [21]:
X[Y == 0][0:1]
# 샘플 하나만 가져올 때

array([[5.1, 3.5, 1.4, 0.2]])

In [56]:
sample = X[Y == 0][0:1]
setosa = X[Y == 0].mean(axis=0)
cos_sim(sample, setosa)
# 유사도

array([0.99987243])

(150, 4) . (4, 1) -> (150, 1)  

(150, 4) . (4, ) -> (150, )


In [13]:
np.dot(X, setosa).shape

(150,)

In [62]:
setosa = X[Y == 0].mean(axis=0)
cos_sim(X, setosa)

array([0.06495663, 0.0605056 , 0.05974857, 0.05884531, 0.06469794,
       0.07046599, 0.06033183, 0.06381371, 0.05584048, 0.06126689,
       0.0687821 , 0.0624121 , 0.05964464, 0.05482247, 0.07303149,
       0.07525832, 0.06950732, 0.06499695, 0.07232561, 0.06692247,
       0.06757557, 0.06640085, 0.06045675, 0.0646727 , 0.0631311 ,
       0.06180556, 0.06413402, 0.06601692, 0.06521531, 0.06046757,
       0.06072625, 0.06717689, 0.06934831, 0.07217283, 0.06130721,
       0.0619708 , 0.06799949, 0.06383698, 0.05616276, 0.06463434,
       0.06393665, 0.05309006, 0.05728667, 0.06477663, 0.06792146,
       0.05972529, 0.06712181, 0.0591676 , 0.06796146, 0.06301209,
       0.0872557 , 0.08189289, 0.08639277, 0.06817064, 0.08070539,
       0.07382   , 0.08215387, 0.06201015, 0.08200732, 0.06775721,
       0.0610623 , 0.07594682, 0.07159087, 0.07818414, 0.07140432,
       0.08351285, 0.07420392, 0.07299903, 0.0746321 , 0.06979486,
       0.0786297 , 0.0759042 , 0.07809726, 0.07754154, 0.07964

In [55]:
setosa = X[Y == 0].mean(axis=0)
versicolor = X[Y == 1].mean(axis=0)
verginica = X[Y == 2].mean(axis=0)

print(setosa)
print(versicolor)
print(verginica)

[5.006 3.428 1.462 0.246]
[5.936 2.77  4.26  1.326]
[6.588 2.974 5.552 2.026]


In [67]:
setosa_cos = cos_sim(X, setosa)
versicolor_cos = cos_sim(X, versicolor)
verginica_cos = cos_sim(X, verginica)

In [81]:
# np.concatenate([setosa_cos, versicolor_cos, verginica_cos], axis=1).shape
# 1차원인라서 오류남.
cos = np.stack([setosa_cos, versicolor_cos, verginica_cos])
cos.shape

(3, 150)

In [82]:
np.sum(np.argmax(cos, axis=0) == Y) / len(Y)
# np.argmax(cos, axis=0) 예측결과
# Y 정답

0.9733333333333334

In [83]:
setosa = X[Y == 0].mean(axis=0)
versicolor = X[Y == 1].mean(axis=0)
verginica = X[Y == 2].mean(axis=0)

setosa_cos = cos_sim(X, setosa)
versicolor_cos = cos_sim(X, versicolor)
verginica_cos = cos_sim(X, verginica)

cos = np.stack([setosa_cos, versicolor_cos, verginica_cos])

np.sum(np.argmax(cos, axis=0) == Y) / len(Y)

0.9733333333333334

In [88]:
np.argmax(cos, axis=0)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 2, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2], dtype=int64)

In [90]:
cos

array([[0.06495663, 0.0605056 , 0.05974857, 0.05884531, 0.06469794,
        0.07046599, 0.06033183, 0.06381371, 0.05584048, 0.06126689,
        0.0687821 , 0.0624121 , 0.05964464, 0.05482247, 0.07303149,
        0.07525832, 0.06950732, 0.06499695, 0.07232561, 0.06692247,
        0.06757557, 0.06640085, 0.06045675, 0.0646727 , 0.0631311 ,
        0.06180556, 0.06413402, 0.06601692, 0.06521531, 0.06046757,
        0.06072625, 0.06717689, 0.06934831, 0.07217283, 0.06130721,
        0.0619708 , 0.06799949, 0.06383698, 0.05616276, 0.06463434,
        0.06393665, 0.05309006, 0.05728667, 0.06477663, 0.06792146,
        0.05972529, 0.06712181, 0.0591676 , 0.06796146, 0.06301209,
        0.0872557 , 0.08189289, 0.08639277, 0.06817064, 0.08070539,
        0.07382   , 0.08215387, 0.06201015, 0.08200732, 0.06775721,
        0.0610623 , 0.07594682, 0.07159087, 0.07818414, 0.07140432,
        0.08351285, 0.07420392, 0.07299903, 0.0746321 , 0.06979486,
        0.0786297 , 0.0759042 , 0.07809726, 0.07

In [124]:
arr1 = np.array([1,2,3,4,5])
arr1

array([1, 2, 3, 4, 5])

In [125]:
arr2 = arr1[1:3].copy()
arr2

array([2, 3])

In [126]:
arr2 *= 10
arr2

array([20, 30])

In [127]:
arr1

array([1, 2, 3, 4, 5])

In [134]:
print(id(arr1[1]))
print(id(arr2[0]))

2278726931824
2278726938800
