In [2]:
import numpy as np

In [2]:
v1 = np.array([1, 5, -4])

arr1 = np.array([[1,2,3],[4,5,6]])
print(v1)
print(arr1)

[ 1  5 -4]
[[1 2 3]
 [4 5 6]]


# 내적

In [3]:
v1 = np.array([1,2,3])
v2 = np.array([5,0,-7])
np.dot(v1, v2)

-16

In [6]:
v1 = np.array([5,0])
v2 = np.array([0,4])
np.dot(v1, v2)

0

In [7]:
v1 = np.array([5,0])
v2 = np.array([-2,4])
np.dot(v1, v2)

-10

In [3]:
arr1 = np.array([[1,2],[3,4],[5,6]])
arr2 = np.array([[6,23],[-1,7],[8,9]])

np.dot(arr1,arr2)

ValueError: shapes (3,2) and (3,2) not aligned: 2 (dim 1) != 3 (dim 0)

In [6]:
np.dot(arr1, arr2.T)

array([[ 52,  13,  26],
       [110,  25,  60],
       [168,  37,  94]])

In [7]:
np.dot(arr1.T, arr2)

array([[ 43,  89],
       [ 56, 128]])

In [14]:
from sklearn.datasets import load_iris

In [21]:
iris = load_iris()
# iris.data
# iris['data']
X = iris.data
Y = iris.target

In [25]:
print(X.shape)
print(Y.shape)

(150, 4)
(150,)


In [31]:
X[Y == 0] # y가 true인 것들만 x에서 가져온다
for i in range(3):
    print(iris.target_names[i])
    print(X[Y == i].mean(axis=0))
    print(X[Y == i].std(axis=0))

setosa
[5.006 3.428 1.462 0.246]
[0.34894699 0.37525458 0.17191859 0.10432641]
versicolor
[5.936 2.77  4.26  1.326]
[0.51098337 0.31064449 0.46518813 0.19576517]
virginica
[6.588 2.974 5.552 2.026]
[0.62948868 0.31925538 0.54634787 0.27188968]


In [36]:
def cos_sim(a, b):
    return np.dot(a, b) / (np.linalg.norm(a) * np.linalg.norm(b)) 
    # 뒤에 거는 벡터 크기 구하는 함수
# cos0 == a.b / |a||b|

In [43]:
sample = X[Y == 2][0]
setosa = X[Y == 0].mean(axis=0)
cos_sim(sample, setosa)
# 유사도

0.868065116199693

In [ ]:
a