* 딥러닝에 입력으로 들어가는 이미지, 4차원 데이터(batch_size, 높이 너비, 채널수)

In [7]:
import numpy as np

In [9]:
import time
start_time = time.time()

numbers = range(1, 1000001)

sqares = []

for num in numbers:
    sqares.append(num**2)

end_time = time.time()
print(end_time - start_time)

0.08262443542480469


In [16]:
import time
import numpy as np
start_time = time.time()

numbers = np.arange(1, 1000001)

squares = np.square(numbers)


end_time = time.time()
print(end_time - start_time)

0.0009999275207519531


In [18]:

arr = np.array([1,2,3,4,5]) # 벡터 1차원
arr2 = np.array([[1,2,3,4,5]])  # 1행 5열 2차원
arr1 = np.array((1,2,3,4,5))
arr
arr1

array([1, 2, 3, 4, 5])

In [23]:
print(arr.shape) # 배열의 형태
print(arr.ndim) # 차원 수
print(arr.dtype) #내부 원소의 자료형
print(arr.itemsize) #내부 원소의 크기(바이트 단위)
print(arr.size) # 내부의 원소 개수

(5,)
1
int32
4
5


In [25]:
arr = np.array([[1],[2],[3],[4],[5]])
arr

array([[1],
       [2],
       [3],
       [4],
       [5]])

In [26]:
print(arr.shape) # 배열의 형태
print(arr.ndim) # 차원 수
print(arr.dtype) #내부 원소의 자료형
print(arr.itemsize) #내부 원소의 크기(바이트 단위)
print(arr.size) # 내부의 원소 개수

(5, 1)
2
int32
4
5


In [31]:
arr = np.array([[1,2,3],
                [1,2,3],
                [1,2,3]])
arr

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [30]:
print(arr.shape) # 배열의 형태
print(arr.ndim) # 차원 수
print(arr.dtype) #내부 원소의 자료형
print(arr.itemsize) #내부 원소의 크기(바이트 단위)
print(arr.size) # 내부의 원소 개수

(3, 3)
2
int32
4
9


In [33]:
arr_3 = np.array([[[1,2], [3,4]],
                  [[5,6], [7,8]]])
arr_3

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [35]:
print(arr_3.shape) # 배열의 형태
print(arr_3.ndim) # 차원 수
print(arr_3.dtype) #내부 원소의 자료형
print(arr_3.itemsize) #내부 원소의 크기(바이트 단위)
print(arr_3.size) # 내부의 원소 개수

(2, 2, 2)
3
int32
4
8


In [47]:
arr_zero = np.zeros((4,3))
arr_zero

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [45]:
arr_zero = np.zeros((4,3), dtype=int) # 요소의 형을 지정할 수 있음, 소수점 날라감
arr_zero

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [51]:
arr_one = np.ones((2,2,3), dtype=str)
arr_one

array([[['1', '1', '1'],
        ['1', '1', '1']],

       [['1', '1', '1'],
        ['1', '1', '1']]], dtype='<U1')

In [52]:
arr_empty = np.empty((2,3)) # 이전 메모리 공간에 남아있던 쓰레기 값이 보임
arr_empty

array([[0., 0., 0.],
       [0., 0., 0.]])

In [54]:
arr_full = np.full((2,2,3), 7) # 2D array with 3 columns and 2 rows
print(arr_full)


[[[7 7 7]
  [7 7 7]]

 [[7 7 7]
  [7 7 7]]]


In [60]:
arr_arange = np.arange(0, 10)  # arange는 1차원으로
arr_arange1 = np.arange(0, 10, 2) # reshape이랑 같이 엮여서 사용됨
arr_arange2 = np.arange(10).reshape(2, 5) # reshape이랑 같이 엮여서 사용됨

print(arr_arange)
print(arr_arange1)
print(arr_arange2)

[0 1 2 3 4 5 6 7 8 9]
[0 2 4 6 8]
[[0 1 2 3 4]
 [5 6 7 8 9]]


In [62]:
import numpy as np
arr_linspace = np.linspace(0, 1, 5) # 0과 1사이를 5개로 나눠서 쪼개는 것

print(arr_linspace)

[0.   0.25 0.5  0.75 1.  ]


In [70]:
arr_linspace2 = np.linspace(0, 2*np.pi, 10) 

print(arr_linspace2)

[0.         0.6981317  1.3962634  2.0943951  2.7925268  3.4906585
 4.1887902  4.88692191 5.58505361 6.28318531]


In [17]:
a = np.array([1,2,3])
b = np.array([4,5,6])
np.dot(a,b)

32

In [14]:
a = np.full((3, 3, 4), 2)
a

array([[[2, 2, 2, 2],
        [2, 2, 2, 2],
        [2, 2, 2, 2]],

       [[2, 2, 2, 2],
        [2, 2, 2, 2],
        [2, 2, 2, 2]],

       [[2, 2, 2, 2],
        [2, 2, 2, 2],
        [2, 2, 2, 2]]])

# 2023.5.11 오후

In [25]:
v1 = np.array([[1,2,3], [4,5,6]]) # 그냥 * 곱하기는 요소 곱하기
v2 = np.array([[4,5,6], [1,0,6]])

print(v1+v2)
print(v1-v2)
print(v1*v2)
print(v1/v2) # 0 나누기 지원함, 다만 infinite 무한으로
print(v1//v2)
print(v1%v2)
print(v1**v2) # 음수 제곱을 지원 안 함.

[[ 5  7  9]
 [ 5  5 12]]
[[-3 -3 -3]
 [ 3  5  0]]
[[ 4 10 18]
 [ 4  0 36]]
[[0.25 0.4  0.5 ]
 [4.    inf 1.  ]]
[[0 0 0]
 [4 0 1]]
[[1 2 3]
 [0 0 0]]
[[    1    32   729]
 [    4     1 46656]]


C:\Users\PC\AppData\Local\Temp\ipykernel_7740\1920066613.py:7: RuntimeWarning: divide by zero encountered in divide
  print(v1/v2) # 0 나누기 지원함, 다만 infinite 무한으로
C:\Users\PC\AppData\Local\Temp\ipykernel_7740\1920066613.py:8: RuntimeWarning: divide by zero encountered in floor_divide
  print(v1//v2)
C:\Users\PC\AppData\Local\Temp\ipykernel_7740\1920066613.py:9: RuntimeWarning: divide by zero encountered in remainder
  print(v1%v2)


In [27]:
v1 + 10 # 브로드캐스팅

array([[11, 12, 13],
       [14, 15, 16]])

In [29]:
v1 ** 2

array([[ 1,  4,  9],
       [16, 25, 36]])

In [30]:
v1 + np.array([10,100,1000]) # 각 열을 다르게 더하기

array([[  11,  102, 1003],
       [  14,  105, 1006]])

In [33]:
v1 + np.array([[10], [100]]) # 각 행을 다르게 더하기

array([[ 11,  12,  13],
       [104, 105, 106]])

In [34]:
v1 > v2

array([[False, False, False],
       [ True,  True, False]])

In [36]:
v1 > 4  # 비교연산자도 브로드캐스팅을 지원

array([[False, False, False],
       [False,  True,  True]])

In [37]:
v1 == 3

array([[False, False,  True],
       [False, False, False]])

In [40]:
v1 % 2

array([[1, 0, 1],
       [0, 1, 0]], dtype=int32)

In [41]:
v1 % 2 == 0

array([[False,  True, False],
       [ True, False,  True]])

# 배열 슬라이싱 인덱싱

* 인덱싱을 하면 차원이 하나 줄어들지만
* 슬라이싱은 차원이 유지됨
* ex) 5차원에서 2개 슬라이싱, 3개 인덱싱하면 결과는 2차원으로 나옴

In [65]:
v1[0, 1]
# 파이썬에서 하던 v1[0][1]도 된다. 0을 반환 뒤 1을 반환. 일처리가 두 번

2

In [76]:
v3 =np.array([[[1, 1, 1, 0],
        [1, 2, 2, 2],
        [1, 6, 8, 3]],

       [[2, 2, 2, 2],
        [2, 2, 2, 2],
        [2, 2, 2, 2]],

       [[3, 3, 3, 3],
        [3, 3, 3, 3],
        [3, 3, 3, 3]]])

v3

array([[[1, 1, 1, 0],
        [1, 2, 2, 2],
        [1, 6, 8, 3]],

       [[2, 2, 2, 2],
        [2, 2, 2, 2],
        [2, 2, 2, 2]],

       [[3, 3, 3, 3],
        [3, 3, 3, 3],
        [3, 3, 3, 3]]])

In [81]:
v3[1,2,3]

array([[3, 3, 3, 3],
       [3, 3, 3, 3],
       [3, 3, 3, 3]])

In [61]:
v1[0:1, 1:]

array([[2, 3]])

In [83]:
v4 = np.full((2,2,2,2), 1)
v4

array([[[[1, 1],
         [1, 1]],

        [[1, 1],
         [1, 1]]],


       [[[1, 1],
         [1, 1]],

        [[1, 1],
         [1, 1]]]])

# 할당 연산자

In [93]:
v1 = np.array([[1,2,3],
                [4,5,6]])
v1[1,1] = 0
v1

array([[1, 2, 3],
       [4, 0, 6]])

In [90]:
v1[0] = 0
v1

array([[0, 0, 0],
       [4, 0, 6]])

In [92]:
v1[:] = 0 # 모든 요소를 0으로 
v1

array([[0, 0, 0],
       [0, 0, 0]])

In [103]:
v1 = np.array([[1,2,3],
                [4,5,6]])
v1

array([[1, 2, 3],
       [4, 5, 6]])

In [105]:
v1[0] = [0,1,2]
v1

array([[0, 1, 2],
       [4, 5, 6]])

In [106]:
v1[:] = [0,1,2]
v1

array([[0, 1, 2],
       [0, 1, 2]])

In [107]:
v1[:] = [[100], [200]]
v1

array([[100, 100, 100],
       [200, 200, 200]])

In [110]:
z1 = np.zeros((2,3,4,5))
z1

array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]])

In [111]:
z1[0, 2, 2] = 1
z1

array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [1., 1., 1., 1., 1.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]])

In [114]:
z1[0, :, : ,1] = 1
z1

array([[[[0., 1., 0., 0., 0.],
         [0., 1., 0., 0., 0.],
         [0., 1., 0., 0., 0.],
         [0., 1., 0., 0., 0.]],

        [[0., 1., 0., 0., 0.],
         [0., 1., 0., 0., 0.],
         [0., 1., 0., 0., 0.],
         [0., 1., 0., 0., 0.]],

        [[0., 1., 0., 0., 0.],
         [0., 1., 0., 0., 0.],
         [1., 1., 1., 1., 1.],
         [0., 1., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]])

In [9]:
z1[0, 1:] = 1
z1

NameError: name 'z1' is not defined

In [10]:
v1 = np.array([[1,2,3],
            [4,5,6]])
v1

array([[1, 2, 3],
       [4, 5, 6]])

In [122]:
v1[:, [0,1]] # Fancy 인덱싱

array([[1, 2],
       [4, 5]])

In [11]:
za = np.linspace(1, 120, 120, dtype=np.int64).reshape((2,3,4,5))
za

array([[[[  1,   2,   3,   4,   5],
         [  6,   7,   8,   9,  10],
         [ 11,  12,  13,  14,  15],
         [ 16,  17,  18,  19,  20]],

        [[ 21,  22,  23,  24,  25],
         [ 26,  27,  28,  29,  30],
         [ 31,  32,  33,  34,  35],
         [ 36,  37,  38,  39,  40]],

        [[ 41,  42,  43,  44,  45],
         [ 46,  47,  48,  49,  50],
         [ 51,  52,  53,  54,  55],
         [ 56,  57,  58,  59,  60]]],


       [[[ 61,  62,  63,  64,  65],
         [ 66,  67,  68,  69,  70],
         [ 71,  72,  73,  74,  75],
         [ 76,  77,  78,  79,  80]],

        [[ 81,  82,  83,  84,  85],
         [ 86,  87,  88,  89,  90],
         [ 91,  92,  93,  94,  95],
         [ 96,  97,  98,  99, 100]],

        [[101, 102, 103, 104, 105],
         [106, 107, 108, 109, 110],
         [111, 112, 113, 114, 115],
         [116, 117, 118, 119, 120]]]], dtype=int64)

In [15]:
za[0, 1, :, [0,1,3,4]]

array([[21, 26, 31, 36],
       [22, 27, 32, 37],
       [24, 29, 34, 39],
       [25, 30, 35, 40]], dtype=int64)

# 불리언 인덱싱

In [25]:
v1 = np.array([[1,2,3],
            [4,5,6]])
v1

array([[1, 2, 3],
       [4, 5, 6]])

In [20]:
mask = v1 % 2 == 0

In [19]:
v1[[[True, False, True], [True, False, True]]]

array([1, 3, 4, 6])

In [29]:
mask = v1 % 2 == 0
v1[mask]
# v1[v1 % 2 == 0] 이렇게도 가능, 저장하지 않고 임시적일 때

array([0, 0, 0])

In [30]:
v1[mask] = 0
v1

array([[1, 0, 3],
       [0, 5, 0]])